### ISSUE TITLE
[INT] Add Mistral integration

### ISSUE THREAD

**Issue by martinibach** [restackio/integrations-typescript#26]
Implement integration for Mistral with [Typescript Client](https://github.com/mistralai/client-ts) for all API endpoints: 

- [Agents Completion](https://docs.mistral.ai/api/#tag/agents)
- [FIM Completion](https://docs.mistral.ai/api/#tag/fim)
- [Embeddings](https://docs.mistral.ai/api/#tag/embeddings)
- [Finetuning](https://docs.mistral.ai/api/#tag/embeddings)
- [Models](https://docs.mistral.ai/api/#tag/models)
- [Files](https://docs.mistral.ai/api/#tag/files)

**Comment by venerjoel99** [comment]
@martinibach I would be interested to work on the Mistral integration

**Comment by martinibach** [comment]
> @martinibach I would be interested to work on the Mistral integration

Awesome! If you need help verifying specs or reviewing the integration, reach out to @leawn .
